<?php

namespace AppBundle\Repository;

/**
 * PoolVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoolVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
